name: Test Installer on Ubuntu 22.04

on:
  push:
    branches:
      - test-installer-workflow
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Every day at 2:00 AM UTC

jobs:
  installer-test:
    name: Run PteroCA Installer on Ubuntu 22.04
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget expect jq

      - name: Download installer script
        run: |
          wget -q https://pteroca.com/installer.sh -O installer.sh
          chmod +x installer.sh

      - name: Run installer with automated input
        run: |
          sudo bash -c './installer.sh' <<< $'2\ntest.pteroca.local\n' | tee installer.log

      - name: Show installer log
        run: cat installer.log

      - name: Check for success
        id: result
        run: |
          if grep -q "PteroCA installation completed successfully" installer.log; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Send result to Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          STATUS="✅ Installer passed"
          if [ "${{ steps.result.outputs.result }}" = "failure" ]; then
            STATUS="❌ Installer failed"
          fi

          LOG=$(cat installer.log | head -c 1900)

          jq -n \
            --arg content "$STATUS" \
            --arg desc "$LOG" \
            '{
              content: $content,
              embeds: [
                {
                  description: ("```log\n" + $desc + "\n```")
                }
              ]
            }' > payload.json

          curl -s -H "Content-Type: application/json" \
               -X POST \
               -d @payload.json \
               "$DISCORD_WEBHOOK"
