name: Test Installer on Ubuntu 22.04

on:
  push:
    branches:
      - test-installer-workflow
  schedule:
    - cron: '0 2 * * *'  # codziennie o 2:00 w nocy
  workflow_dispatch:     # umożliwia ręczne odpalenie z GUI

jobs:
  test-installer:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget expect jq

      - name: Run installer script with automated input
        run: |
          set -e

          # Pobierz skrypt osobno, żeby łatwiej go debugować
          wget -q https://pteroca.com/installer.sh -O installer.sh
          chmod +x installer.sh

          # Uruchom z expectem
          OUTPUT=$(expect -c '
          spawn sudo ./installer.sh
          expect "Select PHP version"
          send "2\r"
          expect "Enter your domain"
          send "test.pteroca.local\r"
          expect eof
          ')

          echo "$OUTPUT" > installer.log

          # Sprawdzenie sukcesu
          if grep -q "PteroCA installation completed successfully" installer.log; then
            echo "✅ Installer passed"
          else
            echo "❌ Installer failed"
            exit 1
          fi

      - name: Send result to Discord (optional)
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          STATUS="✅ Installer passed"
          if ! grep -q "PteroCA installation completed successfully" installer.log; then
            STATUS="❌ Installer failed"W
          fi
          
          # Ogranicz log do 1900 znaków, bez zawieszania JSON-a
          LOG=$(tail -c 1900 installer.log | head -c 1900)
          
          # Zbuduj bezpieczny JSON payload przez jq
          jq -n \
            --arg content "$STATUS" \
            --arg desc "$LOG" \
            '{
              content: $content,
              embeds: [
                {
                  description: ("```log\n" + $desc + "\n```")
                }
              ]
            }' > payload.json

        # Wyślij do Discorda
        curl -H "Content-Type: application/json" \
            -X POST \
            -d @payload.json \
            "$DISCORD_WEBHOOK"

